#!/usr/bin/env python3
"""Generate a 3-tier "tree fabric" topology for HPCC-FS.

Structurally different from the parking-lot (linear chain): a 3-tier tree with a single core
switch, 2 aggregation switches under it, 2 edge switches under each agg, and 2 hosts per edge.
All inter-switch links are 25 Gbps bottlenecks; host links are 100 Gbps. No ECMP (unique
shortest paths between any pair), so the result is interpretable without reverse-engineering a
path hash. Cross-pod paths are 5 switches = exactly at IntHeader::maxHop.

Node layout (15 nodes total):
    0           core
    1, 2        aggs (1 under core; both attach to core)
    3, 4        edges under agg 1
    5, 6        edges under agg 2
    7, 8        hosts under edge 3
    9, 10       hosts under edge 4
    11, 12      hosts under edge 5
    13, 14      hosts under edge 6

LONG flow:   7 -> 13   (pod 1 -> pod 2, crosses 4 bottleneck uplinks: 3-1, 1-0, 0-2, 2-6)
CROSS flows: chosen to contend at distinct uplinks. Each cross has a unique sharing pattern
with the LONG flow. With unique shortest paths the analyzer's max-min oracle is exact.

Default flow set (equal 50 MB, simultaneous start):
    CROSS_A: 8 -> 10    pod1 intra-pod (edge3-edge4): shares 3-1 with LONG
    CROSS_B: 11 -> 13   pod2 intra-pod (edge5-edge6): shares 2-6 with LONG
    CROSS_C: 9 -> 11    cross-pod via edge4-agg1-core-agg2-edge5: shares 1-0 and 0-2 with LONG
That gives LONG with 4 bottleneck-link path; A and B each share 1; C shares 2.

Generates topology/flow/trace/config files just like gen_parking_lot.py, under hpcc-fs/.
"""
import argparse
import os

HPCC_DIR_REL = "hpcc-fs"
HERE = os.path.dirname(os.path.abspath(__file__))

CONFIG_TEMPLATE = """# Tree-fabric topology, stock HPCC (cc_mode {cc_mode}). Generated by gen_tree_fabric.py.
enable_qcn: true
use_dynamic_pfc_threshold: true
pause_time: 5
packet_payload_size: 1000
l2_chunk_size: 4000
l2_ack_interval: 1
l2_back_to_zero: false
topology_file: {d}/topologies/{name}.txt
flow_file: {d}/flows/{name}.txt
trace_file: {d}/traces/{name}_nodes.txt
trace_output_file: {d}/output/{name}/trace.tr
fct_output_file: {d}/output/{name}/fct.txt
pfc_output_file: {d}/output/{name}/pfc.txt
bottleneck_output_file: {d}/output/{name}/bottleneck.txt
simulator_stop_time: {stop}
cc_mode: {cc_mode}
alpha_resume_interval: 1.0
rate_decrease_interval: 4.0
clamp_target_rate: false
rp_timer: 300.0
ewma_gain: 0.00390625
fast_recovery_times: 1
rate_ai: 40Mb/s
rate_hai: 40Mb/s
min_rate: 1000Mb/s
dctcp_rate_ai: 1000Mb/s
error_rate_per_link: 0.0
has_win: 1
global_t: 1
var_win: true
fast_react: true
u_target: 0.95
mi_thresh: 0
int_multi: 4
multi_rate: false
sample_feedback: false
mb_mode: 0
mb_gamma: 1.0
pint_log_base: 1.05
pint_prob: 1.0
rate_bound: true
ack_high_prio: 0
link_down:
  time: 0
  from_node: 0
  to_node: 0
enable_trace: {enable_trace}
kmax_map:
  25000000000: 400
  100000000000: 1600
kmin_map:
  25000000000: 100
  100000000000: 400
pmax_map:
  25000000000: 0.2
  100000000000: 0.2
buffer_size: 4
qlen_mon_file: {d}/output/{name}/qlen.txt
qlen_dump_interval: 1000000
qlen_mon_interval: 10000
qlen_mon_start: 0
qlen_mon_end: 200000000
"""


def build(name, cc_mode=3, flow_size=50_000_000, stop=0.2, bn_delay="0.002ms",
          enable_trace=0):
    # Node ids (15 nodes, switches 0..6, hosts 7..14)
    SW = list(range(7))
    n_nodes = 15
    n_switch = len(SW)

    # Links: (src, dst, rate, delay)
    links = []
    # Core-agg uplinks (bottleneck)
    links.append((0, 1, "25Gbps", bn_delay))
    links.append((0, 2, "25Gbps", bn_delay))
    # Agg-edge uplinks (bottleneck)
    links.append((1, 3, "25Gbps", bn_delay))
    links.append((1, 4, "25Gbps", bn_delay))
    links.append((2, 5, "25Gbps", bn_delay))
    links.append((2, 6, "25Gbps", bn_delay))
    # Edge-host (not bottleneck)
    for edge, hosts in [(3, (7, 8)), (4, (9, 10)), (5, (11, 12)), (6, (13, 14))]:
        for h in hosts:
            links.append((edge, h, "100Gbps", "0.001ms"))

    topo = [f"{n_nodes} {n_switch} {len(links)}",
            " ".join(str(s) for s in SW)]
    topo += [f"{a} {b} {rate} {delay} 0" for (a, b, rate, delay) in links]

    # Flow set: long + three crosses with distinct sharing patterns.
    flow_specs = [
        (7, 13, flow_size, 0.0),    # LONG, path 7-3-1-0-2-6-13, 4 bottleneck uplinks
        (8, 10, flow_size, 0.0),    # CROSS_A, path 8-3-1-4-10, shares 3-1 with LONG
        (11, 13, flow_size, 0.0),   # CROSS_B, path 11-5-2-6-13, shares 2-6 with LONG
        (9, 11, flow_size, 0.0),    # CROSS_C, path 9-4-1-0-2-5-11, shares 1-0 and 0-2 with LONG
    ]
    flow_specs.sort(key=lambda x: x[3])  # binary requires nondecreasing start time
    flow_lines = [str(len(flow_specs))]
    flow_lines += [f"{s} {d} 3 100 {sz} {st:.6f}" for (s, d, sz, st) in flow_specs]

    trace = [str(n_nodes), " ".join(str(i) for i in range(n_nodes))]

    def w(rel, lines):
        path = os.path.join(HERE, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")

    w(f"topologies/{name}.txt", topo)
    w(f"flows/{name}.txt", flow_lines)
    w(f"traces/{name}_nodes.txt", trace)
    cfg = CONFIG_TEMPLATE.format(d=HPCC_DIR_REL, name=name, stop=stop,
                                 cc_mode=cc_mode, enable_trace=enable_trace)
    cfg_path = os.path.join(HERE, "configs", f"hpcc_{name}.yml")
    os.makedirs(os.path.dirname(cfg_path), exist_ok=True)
    with open(cfg_path, "w") as f:
        f.write(cfg)
    print(f"generated {name}: nodes={n_nodes} switches={n_switch} links={len(links)} "
          f"flows={len(flow_specs)} cc_mode={cc_mode} -> configs/hpcc_{name}.yml")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--cc-mode", type=int, default=3, help="3=HPCC, 11=HPCC-FS")
    ap.add_argument("--flow-size", type=int, default=50_000_000)
    ap.add_argument("--stop-time", type=float, default=0.2)
    ap.add_argument("--bn-delay", default="0.002ms")
    ap.add_argument("--enable-trace", type=int, default=0)
    args = ap.parse_args()
    build(args.name, cc_mode=args.cc_mode, flow_size=args.flow_size,
          stop=args.stop_time, bn_delay=args.bn_delay, enable_trace=args.enable_trace)
