#!/usr/bin/env python3
"""Generate a parking-lot (linear multi-bottleneck) scenario for HPCC-FS.

N bottleneck links (25 Gbps) in series via N+1 switches. One "long" flow crosses
all N bottlenecks; one "cross" flow traverses each single bottleneck link. Host
links are 100 Gbps so the inter-switch links are the only bottlenecks.

Emits topology/flow/trace/config files under hpcc-fs/ for a given N.
Non-topology config knobs match algorithm-validation/configs/hpcc_incast.yml so
results are comparable to the validated baseline. cc_mode stays 3 (stock HPCC);
new variants must use a NEW cc_mode, never edit this path.

Knobs for root-cause experiments (window/RTT hypothesis): --bn-delay, --has-win,
--var-win, --suffix (suffix keeps variant configs/outputs from colliding).
"""
import argparse
import os

HPCC_DIR_REL = "hpcc-fs"  # paths in the YAML are relative to examples/hpcc
HERE = os.path.dirname(os.path.abspath(__file__))

CONFIG_TEMPLATE = """# HPCC-FS parking-lot, {n} bottleneck links, stock HPCC (cc_mode 3). Generated by gen_parking_lot.py.
# variant: bn_delay={bn_delay} has_win={has_win} var_win={var_win}
enable_qcn: true
use_dynamic_pfc_threshold: true
pause_time: 5
packet_payload_size: 1000
l2_chunk_size: 4000
l2_ack_interval: 1
l2_back_to_zero: false
topology_file: {d}/topologies/{name}.txt
flow_file: {d}/flows/{name}.txt
trace_file: {d}/traces/{name}_nodes.txt
trace_output_file: {d}/output/{name}/trace.tr
fct_output_file: {d}/output/{name}/fct.txt
pfc_output_file: {d}/output/{name}/pfc.txt
bottleneck_output_file: {d}/output/{name}/bottleneck.txt
simulator_stop_time: {stop}
cc_mode: {cc_mode}
alpha_resume_interval: 1.0
rate_decrease_interval: 4.0
clamp_target_rate: false
rp_timer: 300.0
ewma_gain: 0.00390625
fast_recovery_times: 1
rate_ai: 40Mb/s
rate_hai: 40Mb/s
min_rate: {min_rate}
dctcp_rate_ai: 1000Mb/s
error_rate_per_link: 0.0
has_win: {has_win}
global_t: 1
var_win: {var_win}
fast_react: true
u_target: 0.95
mi_thresh: 0
int_multi: 4
multi_rate: {multi_rate}
sample_feedback: false
mb_mode: {mb_mode}
mb_gamma: {mb_gamma}
fs_alpha: {fs_alpha}
fs_beta: {fs_beta}
fs_init_frac: {fs_init_frac}
fs_disable_window: {fs_disable_window}
pint_log_base: 1.05
pint_prob: 1.0
rate_bound: true
ack_high_prio: 0
link_down:
  time: 0
  from_node: 0
  to_node: 0
enable_trace: {enable_trace}
kmax_map:
  25000000000: 400
  100000000000: 1600
kmin_map:
  25000000000: 100
  100000000000: 400
pmax_map:
  25000000000: 0.2
  100000000000: 0.2
buffer_size: 4
qlen_mon_file: {d}/output/{name}/qlen.txt
qlen_dump_interval: 1000000
qlen_mon_interval: 10000
qlen_mon_start: 0
qlen_mon_end: 200000000
"""


def build(n, flow_size, stop_time, bn_delay, has_win, var_win, suffix,
          long_size=None, cross_size=None, long_start=0.0, cross_start=0.0,
          multi_rate="false", mb_mode=0, mb_gamma=1.0, cross_host_delay="0.001ms",
          enable_trace=0, trace_rx=False, cc_mode=3,
          fs_alpha=0.4, fs_beta=0.226, fs_init_frac=0.5, fs_disable_window="true",
          min_rate="1000Mb/s"):
    long_size = long_size or flow_size
    cross_size = cross_size or flow_size
    name = f"parking_lot_{n}bn{suffix}"
    n_switch = n + 1                 # switches 0..n
    long_src = n + 1
    long_dst = n + 2
    cross = [(n + 3 + 2 * i, n + 4 + 2 * i) for i in range(n)]
    n_nodes = n_switch + 2 + 2 * n

    links = []
    for i in range(n):              # bottleneck inter-switch links
        links.append((i, i + 1, "25Gbps", bn_delay))
    links.append((0, long_src, "100Gbps", "0.001ms"))
    links.append((n_switch - 1, long_dst, "100Gbps", "0.001ms"))
    for i, (cs, cd) in enumerate(cross):
        links.append((i, cs, "100Gbps", cross_host_delay))
        links.append((i + 1, cd, "100Gbps", cross_host_delay))

    topo = [f"{n_nodes} {n_switch} {len(links)}",
            " ".join(str(s) for s in range(n_switch))]
    topo += [f"{a} {b} {rate} {delay} 0" for (a, b, rate, delay) in links]

    # (src, dst, size_bytes, start_s): long flow first, then one cross flow per link
    flow_specs = [(long_src, long_dst, long_size, long_start)]
    flow_specs += [(cs, cd, cross_size, cross_start) for (cs, cd) in cross]
    flow_specs.sort(key=lambda x: x[3])  # simulator requires nondecreasing start time
    flow_lines = [str(len(flow_specs))]
    flow_lines += [f"{s} {d} 3 100 {sz} {st:.6f}" for (s, d, sz, st) in flow_specs]

    if trace_rx:  # trace only receiver hosts -> small trace, per-flow delivered bytes
        rx = [str(d) for (_s, d, _sz, _st) in flow_specs]
        trace = [str(len(rx)), " ".join(rx)]
    else:
        trace = [str(n_nodes), " ".join(str(i) for i in range(n_nodes))]

    def w(rel, lines):
        path = os.path.join(HERE, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")

    w(f"topologies/{name}.txt", topo)
    w(f"flows/{name}.txt", flow_lines)
    w(f"traces/{name}_nodes.txt", trace)
    cfg = CONFIG_TEMPLATE.format(n=n, d=HPCC_DIR_REL, name=name, stop=stop_time,
                                 bn_delay=bn_delay, has_win=has_win, var_win=var_win,
                                 multi_rate=multi_rate, mb_mode=mb_mode, mb_gamma=mb_gamma,
                                 enable_trace=enable_trace, cc_mode=cc_mode,
                                 fs_alpha=fs_alpha, fs_beta=fs_beta, fs_init_frac=fs_init_frac,
                                 fs_disable_window=fs_disable_window, min_rate=min_rate)
    cfg_path = os.path.join(HERE, "configs", f"hpcc_{name}.yml")
    os.makedirs(os.path.dirname(cfg_path), exist_ok=True)
    with open(cfg_path, "w") as f:
        f.write(cfg)
    print(f"generated {name}: nodes={n_nodes} switches={n_switch} links={len(links)} "
          f"flows={len(flow_specs)} bn_delay={bn_delay} has_win={has_win} var_win={var_win} "
          f"-> configs/hpcc_{name}.yml")
    return name


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, nargs="+", default=[2, 3, 4, 5],
                    help="bottleneck-link counts to generate")
    ap.add_argument("--flow-size", type=int, default=50_000_000)
    ap.add_argument("--stop-time", type=float, default=0.2)
    ap.add_argument("--bn-delay", default="0.002ms", help="bottleneck link delay")
    ap.add_argument("--has-win", type=int, default=1, choices=[0, 1])
    ap.add_argument("--var-win", default="true", choices=["true", "false"])
    ap.add_argument("--suffix", default="", help="appended to scenario name")
    ap.add_argument("--long-size", type=int, default=None, help="long-flow bytes (default flow-size)")
    ap.add_argument("--cross-size", type=int, default=None, help="cross-flow bytes (default flow-size)")
    ap.add_argument("--long-start", type=float, default=0.0, help="long-flow start (s)")
    ap.add_argument("--cross-start", type=float, default=0.0, help="cross-flow start (s)")
    ap.add_argument("--multi-rate", default="false", choices=["true", "false"])
    ap.add_argument("--mb-mode", type=int, default=0, choices=[0, 1, 2, 3, 4, 5],
                    help="0=stock,1=k-AI,2=debiased blend,3=resp-weighted MD,4=kth-root MD,5=global share-aware AI")
    ap.add_argument("--mb-gamma", type=float, default=1.0,
                    help="HPCC-MB strength: mode1=AI scale, mode2=blend weight lambda in [0,1]")
    ap.add_argument("--cross-host-delay", default="0.001ms",
                    help="cross-flow host-link delay (inflate to equalize cross RTT to the long flow)")
    ap.add_argument("--enable-trace", type=int, default=0, choices=[0, 1])
    ap.add_argument("--trace-rx", action="store_true", help="trace only receiver hosts (small trace)")
    ap.add_argument("--cc-mode", type=int, default=3, help="3=HPCC (default), 11=HPCC-FS (RCP switch assist)")
    ap.add_argument("--fs-alpha", type=float, default=0.4)
    ap.add_argument("--fs-beta", type=float, default=0.226)
    ap.add_argument("--fs-init-frac", type=float, default=0.5)
    ap.add_argument("--fs-disable-window", default="true", choices=["true", "false"])
    ap.add_argument("--min-rate", default="1000Mb/s")
    args = ap.parse_args()
    for n in args.n:
        build(n, args.flow_size, args.stop_time, args.bn_delay,
              args.has_win, args.var_win, args.suffix,
              args.long_size, args.cross_size, args.long_start, args.cross_start,
              args.multi_rate, args.mb_mode, args.mb_gamma, args.cross_host_delay,
              args.enable_trace, args.trace_rx, args.cc_mode,
              args.fs_alpha, args.fs_beta, args.fs_init_frac, args.fs_disable_window,
              args.min_rate)
