#!/usr/bin/env python3
"""Parameterized fat-tree generator (any even k, defaults to k=4).

Standard k-ary fat-tree:
  (k/2)^2 core switches
  k pods, each with k/2 edge + k/2 agg switches and (k/2)^2 hosts
  Cross-pod path is always edge->agg->core->agg->edge = 5 switches (== IntHeader::maxHop).

Workload: (k/2)*2 inter-pod flows + (k/2)*2 intra-pod different-edge flows + (k/2)*2 same-edge
flows, scaled with k. Hosts and ports chosen so the analyzer's BFS classifier identifies the
inter-pod flows as the multi-bottleneck ("long") class.

Node numbering (for any k):
    cores:  0 .. (k/2)^2 - 1
    aggs:   (k/2)^2 + p*(k/2) + i              (pod p, agg index i in 0..k/2-1)
    edges:  (k/2)^2 + k*(k/2) + p*(k/2) + j    (pod p, edge index j in 0..k/2-1)
    hosts:  base_host + (p*(k/2) + j)*(k/2) + h
            where base_host = (k/2)^2 + k*(k/2) + k*(k/2)
"""
import argparse
import os

HPCC_DIR_REL = "hpcc-fs"
HERE = os.path.dirname(os.path.abspath(__file__))

CONFIG_TEMPLATE = """# k={k} fat-tree, cc_mode {cc_mode}. Generated by gen_fattree.py.
enable_qcn: true
use_dynamic_pfc_threshold: true
pause_time: 5
packet_payload_size: 1000
l2_chunk_size: 4000
l2_ack_interval: 1
l2_back_to_zero: false
topology_file: {d}/topologies/{name}.txt
flow_file: {d}/flows/{name}.txt
trace_file: {d}/traces/{name}_nodes.txt
trace_output_file: {d}/output/{name}/trace.tr
fct_output_file: {d}/output/{name}/fct.txt
pfc_output_file: {d}/output/{name}/pfc.txt
bottleneck_output_file: {d}/output/{name}/bottleneck.txt
simulator_stop_time: {stop}
cc_mode: {cc_mode}
alpha_resume_interval: 1.0
rate_decrease_interval: 4.0
clamp_target_rate: false
rp_timer: 300.0
ewma_gain: 0.00390625
fast_recovery_times: 1
rate_ai: 40Mb/s
rate_hai: 40Mb/s
min_rate: 1000Mb/s
dctcp_rate_ai: 1000Mb/s
error_rate_per_link: 0.0
has_win: 1
global_t: 1
var_win: true
fast_react: true
u_target: 0.95
mi_thresh: 0
int_multi: 4
multi_rate: false
sample_feedback: false
mb_mode: 0
mb_gamma: 1.0
pint_log_base: 1.05
pint_prob: 1.0
rate_bound: true
ack_high_prio: 0
link_down:
  time: 0
  from_node: 0
  to_node: 0
enable_trace: {enable_trace}
kmax_map:
  25000000000: 400
  100000000000: 1600
kmin_map:
  25000000000: 100
  100000000000: 400
pmax_map:
  25000000000: 0.2
  100000000000: 0.2
buffer_size: 4
qlen_mon_file: {d}/output/{name}/qlen.txt
qlen_dump_interval: 1000000
qlen_mon_interval: 10000
qlen_mon_start: 0
qlen_mon_end: 200000000
"""


def build(name, k=4, cc_mode=3, flow_size=50_000_000, stop=0.2, enable_trace=0):
    assert k % 2 == 0 and k >= 2, "k must be even and >= 2"
    half = k // 2
    n_core = half * half
    n_agg = k * half
    n_edge = k * half
    n_host = k * half * half
    n_switch = n_core + n_agg + n_edge
    n_nodes = n_switch + n_host

    def core(i): return i                                  # 0..n_core-1
    def agg(p, i):  return n_core + p * half + i           # pod p, agg slot i
    def edge(p, j): return n_core + n_agg + p * half + j   # pod p, edge slot j
    def host(p, j, h):
        return n_core + n_agg + n_edge + (p * half + j) * half + h

    sw_ids = list(range(n_switch))
    links = []
    # agg-core: agg index i within pod connects to cores [i*half, i*half+half-1]
    for p in range(k):
        for i in range(half):
            for c in range(i * half, (i + 1) * half):
                links.append((core(c), agg(p, i), "25Gbps", "0.002ms"))
    # agg-edge: each agg connects to all edges in its pod
    for p in range(k):
        for i in range(half):
            for j in range(half):
                links.append((agg(p, i), edge(p, j), "25Gbps", "0.002ms"))
    # edge-host
    for p in range(k):
        for j in range(half):
            for h in range(half):
                links.append((edge(p, j), host(p, j, h), "100Gbps", "0.001ms"))

    topo = [f"{n_nodes} {n_switch} {len(links)}",
            " ".join(str(s) for s in sw_ids)]
    topo += [f"{a} {b} {rate} {delay} 0" for (a, b, rate, delay) in links]

    # Workload (matches the k=4 density that produced a clear multi-bottleneck signal):
    #   - First half of pods source one inter-pod flow per edge to their paired pod (p+k/2):
    #     (k/2) pods * (k/2) edges = k^2/4 inter-pod LONG flows (5-switch path each).
    #   - Each of k pods contributes one intra-pod different-edge SHORT flow (3-switch path).
    # Total flows: k^2/4 + k. For k=4 -> 4 + 4 = 8. For k=6 -> 9 + 6 = 15. For k=8 -> 16 + 8 = 24.
    flow_specs = []
    for p in range(k // 2):
        dst_pod = p + k // 2
        for j in range(half):
            s = host(p, j, 0)
            d = host(dst_pod, j, 0)
            flow_specs.append((s, d, flow_size, 0.0))
    for p in range(k):
        if half >= 2:
            s = host(p, 0, half - 1)
            d = host(p, 1, half - 1)
            flow_specs.append((s, d, flow_size, 0.0))
    flow_specs.sort(key=lambda x: x[3])
    flow_lines = [str(len(flow_specs))]
    flow_lines += [f"{s} {d} 3 100 {sz} {st:.6f}" for (s, d, sz, st) in flow_specs]

    trace = [str(n_nodes), " ".join(str(i) for i in range(n_nodes))]

    def w(rel, lines):
        path = os.path.join(HERE, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")

    w(f"topologies/{name}.txt", topo)
    w(f"flows/{name}.txt", flow_lines)
    w(f"traces/{name}_nodes.txt", trace)
    cfg = CONFIG_TEMPLATE.format(k=k, d=HPCC_DIR_REL, name=name, stop=stop,
                                 cc_mode=cc_mode, enable_trace=enable_trace)
    cfg_path = os.path.join(HERE, "configs", f"hpcc_{name}.yml")
    os.makedirs(os.path.dirname(cfg_path), exist_ok=True)
    with open(cfg_path, "w") as f:
        f.write(cfg)
    os.makedirs(os.path.join(HERE, "output", name), exist_ok=True)
    print(f"generated {name}: k={k} nodes={n_nodes} switches={n_switch} links={len(links)} "
          f"flows={len(flow_specs)} cc_mode={cc_mode}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--k", type=int, default=4, help="fat-tree degree (even)")
    ap.add_argument("--cc-mode", type=int, default=3)
    ap.add_argument("--flow-size", type=int, default=50_000_000)
    ap.add_argument("--stop-time", type=float, default=0.2)
    ap.add_argument("--enable-trace", type=int, default=0)
    args = ap.parse_args()
    build(args.name, k=args.k, cc_mode=args.cc_mode, flow_size=args.flow_size,
          stop=args.stop_time, enable_trace=args.enable_trace)
