#!/usr/bin/env python3
"""Generate a standard k=4 fat-tree topology for idea-a fat-tree evaluation.

Structure (canonical):
  4 cores, 4 pods. Each pod has 2 edge + 2 agg switches; each edge connects to 2 hosts.
  Each agg connects to 2 edges in its pod (down) and 2 cores (up).
  Total: 20 switches + 16 hosts = 36 nodes, 48 links.
  Path lengths: same-edge=1 switch, same-pod-diff-edge=3 switches, inter-pod=5 switches
  (== IntHeader::maxHop; do not extend).

Node numbering:
  0..3   cores
  4..11  aggs (pod p has aggs 4+2p, 5+2p; e.g. pod 0 -> 4,5; pod 1 -> 6,7; ...)
  12..19 edges (pod p has edges 12+2p, 13+2p)
  20..35 hosts (edge 12+2p+e has hosts 20+4p+2e, 21+4p+2e)

ECMP: `hpcc-validation.cc` CalculateRoute keeps all equal-cost next hops. The sim picks one per
packet/flow via a 5-tuple hash. The analyzer (BFS) picks one of the equal-cost paths
deterministically; that may differ from the sim's choice, so we treat oracle slowdown as an
approximation and lean on long-vs-short FCT means as the headline.

Default workload (8 flows, equal 50 MB, simultaneous):
  4 LONG inter-pod (5 switches, path crosses 4 bottleneck links: edge-agg, agg-core, core-agg, agg-edge)
  4 SHORT intra-pod diff-edge (3 switches, 2 bottleneck links: edge-agg, agg-edge)
Same-edge flows are excluded for the headline (they exercise no inter-switch bottleneck).
"""
import argparse
import os

HPCC_DIR_REL = "hpcc-fs"
HERE = os.path.dirname(os.path.abspath(__file__))

CONFIG_TEMPLATE = """# k=4 fat-tree, cc_mode {cc_mode}. Generated by gen_fattree_k4.py.
enable_qcn: true
use_dynamic_pfc_threshold: true
pause_time: 5
packet_payload_size: 1000
l2_chunk_size: 4000
l2_ack_interval: 1
l2_back_to_zero: false
topology_file: {d}/topologies/{name}.txt
flow_file: {d}/flows/{name}.txt
trace_file: {d}/traces/{name}_nodes.txt
trace_output_file: {d}/output/{name}/trace.tr
fct_output_file: {d}/output/{name}/fct.txt
pfc_output_file: {d}/output/{name}/pfc.txt
bottleneck_output_file: {d}/output/{name}/bottleneck.txt
simulator_stop_time: {stop}
cc_mode: {cc_mode}
alpha_resume_interval: 1.0
rate_decrease_interval: 4.0
clamp_target_rate: false
rp_timer: 300.0
ewma_gain: 0.00390625
fast_recovery_times: 1
rate_ai: 40Mb/s
rate_hai: 40Mb/s
min_rate: 1000Mb/s
dctcp_rate_ai: 1000Mb/s
error_rate_per_link: 0.0
has_win: 1
global_t: 1
var_win: true
fast_react: true
u_target: 0.95
mi_thresh: 0
int_multi: 4
multi_rate: false
sample_feedback: false
mb_mode: 0
mb_gamma: 1.0
pint_log_base: 1.05
pint_prob: 1.0
rate_bound: true
ack_high_prio: 0
link_down:
  time: 0
  from_node: 0
  to_node: 0
enable_trace: {enable_trace}
kmax_map:
  25000000000: 400
  100000000000: 1600
kmin_map:
  25000000000: 100
  100000000000: 400
pmax_map:
  25000000000: 0.2
  100000000000: 0.2
buffer_size: 4
qlen_mon_file: {d}/output/{name}/qlen.txt
qlen_dump_interval: 1000000
qlen_mon_interval: 10000
qlen_mon_start: 0
qlen_mon_end: 200000000
"""


def build(name, cc_mode=3, flow_size=50_000_000, stop=0.2, enable_trace=0):
    # Topology constants for k=4
    NUM_POD = 4
    cores = [0, 1, 2, 3]
    # aggs[pod] = (agg_lo, agg_hi)
    aggs = [(4 + 2 * p, 5 + 2 * p) for p in range(NUM_POD)]
    edges = [(12 + 2 * p, 13 + 2 * p) for p in range(NUM_POD)]
    hosts = [[(20 + 4 * p + 2 * e, 21 + 4 * p + 2 * e) for e in range(2)]
             for p in range(NUM_POD)]

    n_switch = 20
    n_nodes = 36
    sw_ids = list(range(20))

    links = []
    # agg-core: each agg connects to 2 cores. Canonical mapping: agg index within pod -> cores.
    #   agg with index e in pod p connects to cores [2*e, 2*e+1] (so agg0 -> cores 0,1; agg1 -> cores 2,3)
    for p in range(NUM_POD):
        for e in range(2):
            agg = 4 + 2 * p + e
            for c in (2 * e, 2 * e + 1):
                links.append((c, agg, "25Gbps", "0.002ms"))
    # agg-edge: each agg connects to both edges in its pod
    for p in range(NUM_POD):
        for ae in range(2):
            agg = 4 + 2 * p + ae
            for ee in range(2):
                edge = 12 + 2 * p + ee
                links.append((agg, edge, "25Gbps", "0.002ms"))
    # edge-host
    for p in range(NUM_POD):
        for e in range(2):
            edge = 12 + 2 * p + e
            for h in hosts[p][e]:
                links.append((edge, h, "100Gbps", "0.001ms"))

    topo = [f"{n_nodes} {n_switch} {len(links)}",
            " ".join(str(s) for s in sw_ids)]
    topo += [f"{a} {b} {rate} {delay} 0" for (a, b, rate, delay) in links]

    # Workload: 4 LONG inter-pod + 4 SHORT intra-pod diff-edge.
    # Pair pods 0<->2 and 1<->3 to spread load across cores.
    flow_specs = [
        # LONG inter-pod (5 switches)
        (20, 28, flow_size, 0.0),  # pod 0 edge12 host20 -> pod 2 edge16 host28
        (22, 30, flow_size, 0.0),  # pod 0 edge13 host22 -> pod 2 edge17 host30
        (24, 32, flow_size, 0.0),  # pod 1 edge14 host24 -> pod 3 edge18 host32
        (26, 34, flow_size, 0.0),  # pod 1 edge15 host26 -> pod 3 edge19 host34
        # SHORT intra-pod, different edge (3 switches)
        (21, 23, flow_size, 0.0),  # pod 0: h21 (ed12) -> h23 (ed13)
        (25, 27, flow_size, 0.0),  # pod 1
        (29, 31, flow_size, 0.0),  # pod 2
        (33, 35, flow_size, 0.0),  # pod 3
    ]
    flow_specs.sort(key=lambda x: x[3])
    flow_lines = [str(len(flow_specs))]
    flow_lines += [f"{s} {d} 3 100 {sz} {st:.6f}" for (s, d, sz, st) in flow_specs]

    trace = [str(n_nodes), " ".join(str(i) for i in range(n_nodes))]

    def w(rel, lines):
        path = os.path.join(HERE, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")

    w(f"topologies/{name}.txt", topo)
    w(f"flows/{name}.txt", flow_lines)
    w(f"traces/{name}_nodes.txt", trace)
    cfg = CONFIG_TEMPLATE.format(d=HPCC_DIR_REL, name=name, stop=stop,
                                 cc_mode=cc_mode, enable_trace=enable_trace)
    cfg_path = os.path.join(HERE, "configs", f"hpcc_{name}.yml")
    os.makedirs(os.path.dirname(cfg_path), exist_ok=True)
    with open(cfg_path, "w") as f:
        f.write(cfg)
    os.makedirs(os.path.join(HERE, "output", name), exist_ok=True)
    print(f"generated {name}: nodes={n_nodes} switches={n_switch} links={len(links)} "
          f"flows={len(flow_specs)} cc_mode={cc_mode} -> configs/hpcc_{name}.yml")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--cc-mode", type=int, default=3)
    ap.add_argument("--flow-size", type=int, default=50_000_000)
    ap.add_argument("--stop-time", type=float, default=0.2)
    ap.add_argument("--enable-trace", type=int, default=0)
    args = ap.parse_args()
    build(args.name, cc_mode=args.cc_mode, flow_size=args.flow_size,
          stop=args.stop_time, enable_trace=args.enable_trace)
