#!/usr/bin/env python3
"""Generate a realistic mixed-size workload on the parking-lot N=4 topology.

Pulls flow sizes (and inter-arrival pattern) from the HPCC SIGCOMM'19 Web-Search distribution
in `paper-simulations/traffic/flow_ws_30.txt`. Mapping: hosts 4,6,8,10,12 (sources) cycled,
hosts 5,7,9,11,13,14 (destinations) cycled, so the resulting flow mix exercises both the long
(multi-bottleneck) path 4->5 and short single-bottleneck paths.

Defaults: 30 flows, starts compressed into [0, 5] ms so contention is concentrated.

Reuses the parking-lot N=4 topology generated by gen_parking_lot.py (must be run first).
Produces a new config that just swaps the flow_file.
"""
import argparse
import os
import random

HERE = os.path.dirname(os.path.abspath(__file__))
HPCC_DIR = os.path.abspath(os.path.join(HERE, ".."))
WS_FLOW = os.path.join(HPCC_DIR, "paper-simulations/traffic/flow_ws_30.txt")

PARKING_TOPO_HOSTS_LONG = (5, 6)
PARKING_TOPO_HOSTS_CROSS = [(7, 8), (9, 10), (11, 12), (13, 14)]  # cross flows at N=4

CONFIG_TEMPLATE = """# Mixed-size workload on parking_lot_4bn (Web-Search distribution sample).
# cc_mode {cc_mode}. Generated by gen_mixed_workload.py.
enable_qcn: true
use_dynamic_pfc_threshold: true
pause_time: 5
packet_payload_size: 1000
l2_chunk_size: 4000
l2_ack_interval: 1
l2_back_to_zero: false
topology_file: hpcc-fs/topologies/parking_lot_4bn.txt
flow_file: hpcc-fs/flows/{name}.txt
trace_file: hpcc-fs/traces/parking_lot_4bn_nodes.txt
trace_output_file: hpcc-fs/output/{name}/trace.tr
fct_output_file: hpcc-fs/output/{name}/fct.txt
pfc_output_file: hpcc-fs/output/{name}/pfc.txt
bottleneck_output_file: hpcc-fs/output/{name}/bottleneck.txt
simulator_stop_time: 0.2
cc_mode: {cc_mode}
alpha_resume_interval: 1.0
rate_decrease_interval: 4.0
clamp_target_rate: false
rp_timer: 300.0
ewma_gain: 0.00390625
fast_recovery_times: 1
rate_ai: 40Mb/s
rate_hai: 40Mb/s
min_rate: 1000Mb/s
dctcp_rate_ai: 1000Mb/s
error_rate_per_link: 0.0
has_win: 1
global_t: 1
var_win: true
fast_react: true
u_target: 0.95
mi_thresh: 0
int_multi: 4
multi_rate: false
sample_feedback: false
mb_mode: 0
mb_gamma: 1.0
pint_log_base: 1.05
pint_prob: 1.0
rate_bound: true
ack_high_prio: 0
link_down: {{ time: 0, from_node: 0, to_node: 0 }}
enable_trace: 0
kmax_map: {{ 25000000000: 400, 100000000000: 1600 }}
kmin_map: {{ 25000000000: 100, 100000000000: 400 }}
pmax_map: {{ 25000000000: 0.2, 100000000000: 0.2 }}
buffer_size: 4
qlen_mon_file: hpcc-fs/output/{name}/qlen.txt
qlen_dump_interval: 1000000
qlen_mon_interval: 10000
qlen_mon_start: 0
qlen_mon_end: 200000000
"""


def sample_sizes(path, n_flows, rng, max_size=None):
    """Stream the WS flow file, sample sizes uniformly (reservoir-like)."""
    sizes = []
    with open(path) as f:
        header = f.readline()
        for i, line in enumerate(f):
            cols = line.split()
            if len(cols) < 6:
                continue
            sz = int(cols[4])
            if max_size and sz > max_size:
                continue
            sizes.append(sz)
            if len(sizes) > n_flows * 200:  # sample pool 200x
                break
    rng.shuffle(sizes)
    return sizes[:n_flows]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True)
    ap.add_argument("--cc-mode", type=int, default=3)
    ap.add_argument("--n-flows", type=int, default=30)
    ap.add_argument("--start-window-ms", type=float, default=5.0,
                    help="spread flow starts over [0, this] ms")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--max-size", type=int, default=10_000_000,
                    help="cap individual flow size (bytes); WS has very large tails")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    sizes = sample_sizes(WS_FLOW, args.n_flows, rng, max_size=args.max_size)
    if not sizes:
        raise SystemExit(f"failed to sample sizes from {WS_FLOW}")

    # Map flows to host pairs: 1/4 to long path, 3/4 spread across cross paths.
    pairs = []
    for i in range(args.n_flows):
        if i % 4 == 0:
            pairs.append(PARKING_TOPO_HOSTS_LONG)  # long flow
        else:
            pairs.append(PARKING_TOPO_HOSTS_CROSS[i % len(PARKING_TOPO_HOSTS_CROSS)])

    # Random start times in [0, start_window]
    starts = sorted(rng.uniform(0.0, args.start_window_ms * 1e-3) for _ in range(args.n_flows))

    # Write flow file
    flow_lines = [str(args.n_flows)]
    for (sz, (s, d), st) in zip(sizes, pairs, starts):
        flow_lines.append(f"{s} {d} 3 100 {sz} {st:.6f}")
    flow_path = os.path.join(HERE, "flows", f"{args.name}.txt")
    os.makedirs(os.path.dirname(flow_path), exist_ok=True)
    with open(flow_path, "w") as f:
        f.write("\n".join(flow_lines) + "\n")

    # Write config
    cfg_path = os.path.join(HERE, "configs", f"hpcc_{args.name}.yml")
    os.makedirs(os.path.dirname(cfg_path), exist_ok=True)
    with open(cfg_path, "w") as f:
        f.write(CONFIG_TEMPLATE.format(cc_mode=args.cc_mode, name=args.name))

    # Stats
    n_long = sum(1 for p in pairs if p == PARKING_TOPO_HOSTS_LONG)
    print(f"generated {args.name}: n_flows={args.n_flows} long_flows={n_long} "
          f"cc_mode={args.cc_mode} sizes range=[{min(sizes)},{max(sizes)}] median={sorted(sizes)[len(sizes)//2]}")


if __name__ == "__main__":
    main()
